services:
  front:
    build: ./red-tetris-front/
    container_name: nuxt
    restart: always
    volumes:
    - ./red-tetris-front:/app
    ports:
    - '3000:3000'
    environment:
      PORT: 3000
      WS_PORT: 81
      BACKEND_URL: 'http://localhost'
    command: "npm run start"
  back:
    build: ./red-tetris-back/
    container_name: nest
    restart: always
    volumes:
      - ./red-tetris-back:/app
    ports:
      - '4000:4000'
      - '81:81'
    environment:
      PORT: 4000
      WS_PORT: 81
    command: "npm run start:dev"